sudo: required
services:
  - docker

before_install:
  - docker build -t lmanyange/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lmanyange/react-test npm test -- --coverage

after_success:
  - docker build -t lmanyange/multi-client ./client
  - docker build -t lmanyange/multi-nginx ./nginx
  - docker build -t lmanyange/multi-server ./server
  - docker build -t lmanyange/multi-worker ./worker
  # Login to Docker CLI -- updated the username and password in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to docker hub
  - docker push lmanyange/multi-client
  - docker push lmanyange/multi-nginx
  - docker push lmanyange/multi-server
  - docker push lmanyange/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: af-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-af-south-1-403524832661
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
